`default_nettype none

//=============================================================================
// Formal cover harness for i2c_master_top_formal
//=============================================================================
// Purpose:
//   - Drive a deterministic Wishbone command script
//   - Cover representative top-level behavior through meaningful milestones
//
// Script outline:
//   1) Program prescaler low/high bytes
//   2) Enable core + interrupt
//   3) Load TX register
//   4) Issue START+WRITE command
//   5) Wait for first IRQ edge, then ACK/clear IRQ
//   6) Issue STOP command and wait for another IRQ edge
//   7) Reach idle terminal state
//
module i2c_master_top_cover_formal;
  (* gclk *) logic wb_clk_i;

  // Reset is symbolic; bus request signals are generated by scripted FSM below.
  (* anyseq *) logic wb_rst_i;
  (* anyseq *) logic arst_i;
  logic [2:0] wb_adr_i;
  logic [7:0] wb_dat_i;
  wire [7:0] wb_dat_o;
  logic wb_we_i;
  logic wb_stb_i;
  logic wb_cyc_i;
  wire wb_ack_o;
  wire wb_inta_o;

  wire scl_pad_i;
  wire scl_pad_o;
  wire scl_padoen_o;
  wire sda_pad_i;
  wire sda_pad_o;
  wire sda_padoen_o;

  // Symbolic external pull-downs for open-drain bus lines.
  (* anyseq *) logic ext_scl_low;
  (* anyseq *) logic ext_sda_low;

  // Open-drain line model for sampled pad inputs.
  assign scl_pad_i = (scl_padoen_o == 1'b0) ? 1'b0 : (ext_scl_low ? 1'b0 : 1'b1);
  assign sda_pad_i = (sda_padoen_o == 1'b0) ? 1'b0 : (ext_sda_low ? 1'b0 : 1'b1);

  i2c_master_top_formal dut (
      .wb_clk_i(wb_clk_i),
      .wb_rst_i(wb_rst_i),
      .arst_i(arst_i),
      .wb_adr_i(wb_adr_i),
      .wb_dat_i(wb_dat_i),
      .wb_dat_o(wb_dat_o),
      .wb_we_i(wb_we_i),
      .wb_stb_i(wb_stb_i),
      .wb_cyc_i(wb_cyc_i),
      .wb_ack_o(wb_ack_o),
      .wb_inta_o(wb_inta_o),
      .scl_pad_i(scl_pad_i),
      .scl_pad_o(scl_pad_o),
      .scl_padoen_o(scl_padoen_o),
      .sda_pad_i(sda_pad_i),
      .sda_pad_o(sda_pad_o),
      .sda_padoen_o(sda_padoen_o)
  );

  // Script state machine for Wishbone traffic generation.
  localparam logic [3:0] StPrerLo = 4'd0;
  localparam logic [3:0] StPrerHi = 4'd1;
  localparam logic [3:0] StCtr = 4'd2;
  localparam logic [3:0] StTxr = 4'd3;
  localparam logic [3:0] StCmdWrite = 4'd4;
  localparam logic [3:0] StWaitIrq1 = 4'd5;
  localparam logic [3:0] StCmdIack = 4'd6;
  localparam logic [3:0] StCmdStop = 4'd7;
  localparam logic [3:0] StWaitIrq2 = 4'd8;
  localparam logic [3:0] StIdle = 4'd9;

  logic [3:0] state;
  logic [1:0] irq_edge_count;
  logic prev_inta;

  // Same reset envelope as prove harness.
  always @(posedge wb_clk_i) begin
    if ($initstate) begin
      assume(wb_rst_i);
      assume(arst_i == 1'b0);
    end else begin
      assume(!wb_rst_i);
      assume(arst_i == 1'b1);
    end
  end

  // Combinational bus driver for each script state.
  always_comb begin
    wb_we_i = 1'b0;
    wb_stb_i = 1'b0;
    wb_cyc_i = 1'b0;
    wb_adr_i = 3'b000;
    wb_dat_i = 8'h00;

    case (state)
      StPrerLo: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b000;
        wb_dat_i = 8'h04;
      end
      StPrerHi: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b001;
        wb_dat_i = 8'h00;
      end
      StCtr: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b010;
        wb_dat_i = 8'hC0;
      end
      StTxr: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b011;
        wb_dat_i = 8'hA0;
      end
      StCmdWrite: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b100;
        wb_dat_i = 8'h90;
      end
      StCmdIack: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b100;
        wb_dat_i = 8'h01;
      end
      StCmdStop: begin
        wb_we_i = 1'b1;
        wb_stb_i = 1'b1;
        wb_cyc_i = 1'b1;
        wb_adr_i = 3'b100;
        wb_dat_i = 8'h40;
      end
      default: begin
      end
    endcase
  end

  // Sequencer:
  // - Advances on WB acks
  // - Tracks rising edges of interrupt output
  always @(posedge wb_clk_i) begin
    if (wb_rst_i || (arst_i == 1'b0)) begin
      state <= StPrerLo;
      irq_edge_count <= 2'd0;
      prev_inta <= 1'b0;
    end else begin
      prev_inta <= wb_inta_o;
      if (wb_inta_o && !prev_inta && irq_edge_count != 2'd3) begin
        irq_edge_count <= irq_edge_count + 2'd1;
      end

      case (state)
        StPrerLo: if (wb_ack_o) state <= StPrerHi;
        StPrerHi: if (wb_ack_o) state <= StCtr;
        StCtr: if (wb_ack_o) state <= StTxr;
        StTxr: if (wb_ack_o) state <= StCmdWrite;
        StCmdWrite: if (wb_ack_o) state <= StWaitIrq1;
        StWaitIrq1: if (irq_edge_count >= 2'd1) state <= StCmdIack;
        StCmdIack: if (wb_ack_o) state <= StCmdStop;
        StCmdStop: if (wb_ack_o) state <= StWaitIrq2;
        StWaitIrq2: if (irq_edge_count >= 2'd2) state <= StIdle;
        default: state <= StIdle;
      endcase
    end
  end

  // Safety checks retained in cover mode to avoid nonsense traces.
  always @(posedge wb_clk_i) begin
    assert(scl_pad_o == 1'b0);
    assert(sda_pad_o == 1'b0);
    assert((scl_padoen_o != 1'b0) || (scl_pad_i == 1'b0));
    assert((sda_padoen_o != 1'b0) || (sda_pad_i == 1'b0));

    if (!$initstate) begin
      assert(!(wb_ack_o && !(wb_cyc_i && wb_stb_i)));
    end
  end

  // Coverage goals for transaction milestones and observable side effects.
  always @(posedge wb_clk_i) begin
    if (!wb_rst_i && (arst_i == 1'b1)) begin
      // Script progression and activity observations.
      cover(state == StWaitIrq1);
      cover(scl_padoen_o == 1'b0);
      cover(sda_padoen_o == 1'b0);
      // Observe at least two interrupt events over the script.
      cover(irq_edge_count >= 2'd1);
      cover(irq_edge_count >= 2'd2);
      cover(wb_inta_o);
      // Terminal script completion.
      cover(state == StIdle);
    end
  end
endmodule

`default_nettype wire
