`default_nettype none

//=============================================================================
// Formal Verification Harness for UART Receiver
//=============================================================================
// This harness verifies the correctness of uart_rx using formal methods.
//
// Verification strategy:
//   1. Generate a valid UART frame on rx_serial (start, 8 data bits, stop)
//   2. Drive rx_serial with expected bit sequence
//   3. Assert that rx_data matches the transmitted payload when rx_valid
//   4. Verify rx_busy flag behavior throughout reception
//
// Uses reduced clock and baud parameters for faster verification.
//=============================================================================

module uart_rx_formal;
  // Reduced parameters for faster formal verification
  localparam int ClkHz = 100;              // Clock frequency
  localparam int Baud = 10;                // Baud rate
  localparam int BaudDiv = ClkHz / Baud;   // Clock cycles per bit = 10

  // Clock and reset
  (* gclk *) logic clk;  // Global clock for formal verification
  logic rst;

  // Test stimulus and DUT signals
  (* anyseq *) logic [7:0] rx_payload;  // Arbitrary data for symbolic execution
  logic rx_serial;   // Driven serial input (generated by harness)
  wire [7:0] rx_data;  // Received data output from DUT
  wire rx_valid;       // Valid flag from DUT
  wire rx_busy;        // Busy flag from DUT

  uart_rx #(
      .CLK_HZ(ClkHz),
      .BAUD(Baud)
  ) dut (
      .clk(clk),
      .rst(rst),
      .rx_serial(rx_serial),
      .rx_data(rx_data),
      .rx_valid(rx_valid),
      .rx_busy(rx_busy)
  );

  //===========================================================================
  // Verification State Tracking
  //===========================================================================
  logic [7:0] rx_latched;  // Latched copy of rx_payload to compare against
  integer phase_cnt;       // Phase counter: tracks cycle within frame
  logic active;            // Indicates frame transmission in progress
  logic fired;             // Indicates frame generation has started

  //===========================================================================
  // Expected Bit Function
  //===========================================================================
  // Returns the expected bit value for each position in the UART frame:
  //   idx 0:    Start bit (0)
  //   idx 1-8:  Data bits (LSB first)
  //   idx 9:    Stop bit (1)
  function automatic logic expected_bit(input integer idx);
    if (idx == 0) begin
      expected_bit = 1'b0;  // Start bit
    end else if (idx >= 1 && idx <= 8) begin
      expected_bit = rx_latched[idx - 1];  // Data bits (LSB first)
    end else begin
      expected_bit = 1'b1;  // Stop bit
    end
  endfunction

  //===========================================================================
  // Reset Assumptions
  //===========================================================================
  // Ensure reset is active at initialization, then deasserted
  always_ff @(posedge clk) begin
    if ($initstate) begin
      assume(rst);   // Reset must be active initially
    end else begin
      assume(!rst);  // After init, reset is deasserted
    end
  end

  //===========================================================================
  // Frame Generation Tracking Logic
  //===========================================================================
  // Track frame generation progress and latch data for verification
  always_ff @(posedge clk) begin
    if (rst) begin
      rx_latched <= 8'd0;
      phase_cnt <= 0;
      active <= 1'b0;
      fired <= 1'b0;
    end else begin
      if (!fired) begin
        fired <= 1'b1;            // Mark that frame generation has started
        rx_latched <= rx_payload;  // Latch the payload to send
        phase_cnt <= -1;           // Initialize phase counter
        active <= 1'b1;            // Mark frame as active
      end else if (active) begin
        phase_cnt <= phase_cnt + 1;  // Increment phase through frame
      end

      // Deactivate after full frame (10 bits)
      if (active && (phase_cnt == (BaudDiv * 10 - 1))) begin
        active <= 1'b0;
      end
    end
  end

  //===========================================================================
  // RX Serial Signal Generation
  //===========================================================================
  // Drive rx_serial with the expected UART frame bit sequence
  always_comb begin
    integer bit_idx;
    integer phase_cnt_adj;
    rx_serial = 1'b1;  // Default: line idles high
    bit_idx = 0;
    phase_cnt_adj = phase_cnt + 1;
    if (active && (phase_cnt_adj >= 1)) begin
      // Calculate which bit of the frame we're transmitting
      bit_idx = (phase_cnt_adj - 1) / BaudDiv;
      rx_serial = expected_bit(bit_idx);  // Drive with expected bit
    end
  end

  //===========================================================================
  // Formal Verification Assertions and Coverage
  //===========================================================================
  always_comb begin
    integer phase_cnt_adj;
    integer last_phase;
    phase_cnt_adj = phase_cnt + 1;
    last_phase = (BaudDiv * 10);
    if (!rst) begin
      // Coverage points: verify all signal states are reachable
      cover (rx_valid == 1'b0);
      cover (rx_valid == 1'b1);
      cover (rx_busy == 1'b0);
      cover (rx_busy == 1'b1);
      cover (rx_data == 8'h00);  // Test with all zeros
      cover (rx_data == 8'hA5);  // Test with alternating bits

      // Assertions: verify behavior
      if (!fired) begin
        assert (rx_busy == 1'b0);  // Not busy before reception starts
      end
      if (rx_valid) begin
        assert (rx_busy == 1'b0);  // Not busy when valid
        assert (rx_data == rx_latched);  // Data matches transmitted payload
      end
    end
  end
endmodule

`default_nettype wire
